apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluent-bit
spec:
  interval: 10m0s
  path: ./clusters/oreilly-cluster/observability/fluent-bit
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
