apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
spec:
  interval: 10m0s
  path: ./clusters/oreilly-cluster/observability/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
